% Generated by r6-generator-maven-plugin: do not edit by hand

\name{J${class.getSimpleName()}$${method.getName()}}
\alias{${method.getName()}}
<#list method.getList("aliases") as alias>
\alias{${alias}}
</#list>
\title{${method.getValue("title")}}
\usage{
  J${class.getSimpleName()}$${method.getName()}(<#list method.getParameterNames() as paramName>${paramName}<#sep>, </#list>)
}
\arguments{
<#list method.getParameterNames() as paramName>
	\item{${method.getParameterDescription(paramName)}}{ - (java expects a ${method.getParameterType(paramName)})}
</#list>
}
\description{
${method.getValue("description")!}
}
\examples{\dontrun{
<#list method.getList("examples") as example>
${example}
</#list>
}
\value{
	<#if method.isFluent()>
		a J${class.getSimpleName()} instance: ${method.getValue("return")!}
	<#else>
		${method.getReturnType()}: ${method.getValue("return")!}
	</#if>
}
}
\keyword{java api}