# generated by r6-generator-maven-plugin
^.*\.Rproj$
^\.Rproj\.user$
^_pkgdown\.yml$
^docs$
^pkgdown$
# java maven directory layouts
^src$
^target$
pom.xml
.classpath
index.html
^.github$
# created in rJava setup on github workflow.
^reconf.sh$