% Generated by r6-generator-maven-plugin: do not edit by hand
\docType{package}
\name{${model.getConfig().getPackageName()}-package}
\alias{${model.getConfig().getPackageName()}}
\alias{${model.getConfig().getPackageName()}-package}
\title{${model.getConfig().getPackageName()}: ${model.getConfig().getTitle()!}}
\description{
\if{html}{\figure{logo.png}{options: align='right'}}
${model.getConfig().getDescription()!}

Version: ${model.getConfig().getVersion()}

Classes:
\itemize{ 
	\item \code{JavaApi}
	<#list model.getClassTypes() as class>
	\item \code{${class.getSimpleName()}}
	</#list>
}
}

\author{
\itemize{ 
	<#list model.getAuthors() as author>
   \item ${author[0]} ${author[1]!} ${author[2]!} ${author[3]!}
	</#list>
}
}

\keyword{java api}