# Generated by roxygen2: do not edit by hand
# But actually generated by r6-generator-maven-plugin
export(JavaApi)
<#list model.getExports() as export>
export(${export})
</#list>
<#list model.getImports() as import>
import(${import})
</#list>
import(rJava)