# Generated by r6-generator-maven-plugin: remove this line if you want to make manual changes and dont want them to get overwritten
^.*\.Rproj$
^\.Rproj\.user$
^_pkgdown\.yml$
^docs$
^pkgdown$
# java maven directory layouts

^target$

# The following ignores can be used if we are deploying the fat jar to CRAN or github 
# ^src$
# pom.xml
# mvnw
# mvnw.cmd

.classpath
index.html
^.github$

# created during rJava setup on github workflow.
^reconf.sh$