# Generated by maven-r-jsr223-plugin: do not edit by hand

# This runs when the library is loaded.
# The precise result of this is a little uncertain as it depends on whether rJava has already been
# initialised and what other libraries are using it.
.onLoad <- function(libname, pkgname) {
	<#if model.getConfig().hasRJavaOpts()>
	# add in specific java options from the maven file
	options(java.parameters = c(getOption("java.parameters"),"<#list model.getConfig().getRJavaOpts() as jopt>${jopt}<#sep>", "</#list>"))
	</#if>
}
