% Generated by maven-r-jsr223-plugin: do not edit by hand

\name{JavaApi}

\alias{JavaApi}

\title{}

\usage{\preformatted{
library(${model.getConfig().getPackageName()})
J = JavaApi$new();
}}

\description{
	${model.getConfig().getDescription()}
}

\keyword{java api}

\section{Methods}{
	\subsection{Public methods}{
		\itemize{
			\item \code{JavaApi$new()}
<#list model.getClassTypes() as class>
	<#list class.getConstructors() as method>
			\item \href{#method-${class.getName()}-new}{\code{J$${class.getName()}$${method.getName()}(${method.getParameterCsv()})}}
	</#list>
	<#list class.getStaticMethods() as method>
			\item \href{#method-${class.getName()}-${method.getName()}}{\code{J$${class.getName()}$${method.getName()}(${method.getParameterCsv()})}}
	</#list>
</#list>
		}
	}

<#list model.getClassTypes() as class>
<#list class.getConstructorsAndStaticMethods() as method>
	\if{html}{\out{<hr>}}
	\if{html}{\out{<a id="method-${method.getName()}"></a>}}
	
	\subsection{Method \code{${class.getName()}$${method.getName()}()}}{
		${method.getDescription()}
	}

	\subsection{Usage}{
		\if{html}{\out{<div class="r">}}
		\preformatted{
	<#if method.isStatic()>
  library(${model.getConfig().getPackageName()})
  J <- JavaApi$new()
  J$${class.getName()}$${method.getName()}(${method.getParameterCsv()})
	<#else>
  library(${model.getConfig().getPackageName()})
  J <- JavaApi$new()
  instance <- J$${class.getName()}$new(...);
  instance$${method.getName()}(<#list method.getParameterNames() as paramName>${paramName}<#sep>, </#list>)
  	</#if>
		}
		\if{html}{\out{</div>}}
	}
	
	\subsection{Arguments}{
		\if{html}{\out{<div class="arguments">}}
		\describe{
			\itemize{
	<#list method.getParameterNames() as paramName>
				\item{${method.getParameterDescription(paramName)}}{ - (java expects a ${method.getParameterType(paramName)})}
	</#list>
			}
		}
		\if{html}{\out{</div>}}
	}

	\subsection{Returns}{
	<#if method.isFactory()>
		R6 ${method.getReturnSimple()} object: ${method.getValue("return")!}
	<#else>
		${method.getReturnType()}: ${method.getValue("return")!}
	</#if>
	}

	\subsection{Examples}{
		\if{html}{\out{<div class="r example copy">}}
		\preformatted{
	<#list method.getList("examples") as example>
  ${example}
	</#list>
		}
		\if{html}{\out{</div>}}
	}
</#list>
</#list>
}