# Generated by maven-r-jsr223-plugin: do not edit by hand
# returns a reference to a java class in a jsr223 engine
JavaApi = R6::R6Class("JavaApi", public=list( 
	#### fields ----
	.engine = NULL,
	.objId = 0,
<#list model.getClassTypes() as class>
	${class.getName()} = NULL,
</#list>
  
 	#### constructor ----
 	initialize = function() {
	
	# initialise java engine
	
	class.path <- c(
		system.file("java", "groovy-all-2.4.17.jar", package="${model.getConfig().getPackageName()}"),
		system.file("java", "${jarFileName}", package="${model.getConfig().getPackageName()}")
	)	
	self$.engine = jsr223::ScriptEngine$new("groovy", class.path)
	self$.engine$setDataFrameRowMajor(FALSE)
	# set up engine
	self$.engine %@% '
		objs = [];
		nextObjId = 0;
	'
	
	# initialise constructor and static class definitions
<#list model.getClassTypes() as class>
	self$${class.getName()} = list(
	<#list class.getConstructors() as method>
		new = function(${method.getParameterCsv()}) {
			# constructor
			# copy parameters
		<#list method.getParameterNames() as param>
			self$.engine$tmp_${param} = ${param};
		</#list>
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = new ${class.getClassName()}(${method.getParameterCsv("tmp_")});
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# delete parameters
		<#list method.getParameterNames() as param>
			self$.engine$remove("tmp_${param}")
		</#list>
			return(${class.getName()}$new(self$.engine, objId))
		}<#sep>,
	</#list>
	<#if (class.hasStaticMethods())>,</#if>
	<#list class.getStaticMethods() as method>
		${method.getName()} = function(${method.getParameterCsv()}) {
			# copy parameters
			<#list method.getParameterNames() as param>
			self$.engine$tmp_${param} = ${param};
			</#list>
			#execute static call
		 	<#if method.isFactory()>
			# execute static method and return pointer to create objId   
			objId = self$.engine %~% '
				synchronized(objs) {
					objs[nextObjId] = ${class.getClassName()}.${method.getName()}(${method.getParameterCsv("tmp_")});
					nextObjId = nextObjId+1 
				}
				return nextObjId-1;
			'
			# wrap resulting id in R class
			# TODO: this maybe create multiple copies of a java object in R. Possibly should maintain a lookup.
			out = ${method.getReturnSimple()}$new(self$.engine, objId)
			<#else>
			# execute static method
			out = self$.engine %~% '
				return ${class.getClassName()}.${method.getName()}(${method.getParameterCsv("tmp_")});
			'
		</#if>
			# delete parameters
		<#list method.getParameterNames() as param>
			self$.engine$remove("tmp_${param}")
		</#list>
			<#if method.getReturnType() != "void">return(out)<#else>invisible(NULL)</#if>
			# TODO: fluent methods should return invisible(self) or a reference to the same object
		}<#sep>,
	</#list>
	)
</#list>
	}
  
  
))

<#list model.getClassTypes() as class>
${class.getName()} = R6::R6Class("${class.getName()}", public=list(
	.engine = NULL,
	.objId = NULL,
	initialize = function(engine,objectId){
		self$.engine = engine;
		self$.objId = objectId;
	},
	<#list class.getInstanceMethods() as method>
	${method.getName()} = function(${method.getParameterCsv()}) {
		# copy parameters
		<#list method.getParameterNames() as param>
		self$.engine$tmp_${param} = ${param};
		</#list>
		self$.engine$tmp2_objId = self$.objId;
		<#if method.isFactory()>
		#execute call on instance _objId returninf a new objId   
		objId = self$.engine %~% '
			synchronized(objs) {
				objs[nextObjId] = objs[tmp2_objId].${method.getName()}(${method.getParameterCsv("tmp_")});
				nextObjId = nextObjId+1 
			}
			return nextObjId-1;
		'
		# wrap resulting id in R class
		# TODO: this maybe create multiple copies of a java object in R. Possibly should maintain a lookup.
		out = ${method.getReturnSimple()}$new(self$.engine, objId)
		<#else>
		#execute call on instance _objId returning a result
		out = self$.engine %~% '
			return objs[tmp2_objId].${method.getName()}(${method.getParameterCsv("tmp_")});
		'
		</#if>
		# delete parameters
		self$.engine$remove("tmp2_objId")
		<#list method.getParameterNames() as param>
		self$.engine$remove("tmp_${param}")
		</#list>
		<#if method.getReturnType() != "void">return(out)<#else>invisible(NULL)</#if>
		# TODO: fluent methods should return invisible(self) or a reference to the same object
	},
	</#list>
	print = function() {
		self$.engine$tmp2_objId = self$.objId;
		out = self$.engine %~% '
			return objs[tmp2_objId].toString();
		'
		self$.engine$remove("tmp2_objId")
		print(out)
		invisible(self)
	}
))

</#list>