% Generated by maven-r-jsr223-plugin: do not edit by hand
\name{${method.getName()}}
<#list method.getList("aliases") as alias>
\alias{${alias}}
</#list>
\title{${method.getValue("title")}}
\usage{

}
\arguments{
\item{api}{the java api object}
<#list method.getParameterNames() as paramName>
\item{${paramName}}{expects a ${method.getParameterTypes()[paramName?index]}}
</#list>
}
\description{
${method.getValue("description")!}
}
\examples{
<#list method.getList("examples") as example>
${example}
</#list>
}
\value{${method.getReturnType()} : ${method.getValue("returns")!}}
\keyword{java api}
