# Generated by maven-r-jsr223-plugin: do not edit by hand

export(java${class.getName()})
<#list class.getMethods() as method>
export(${method.getName()})
</#list>
<#list class.getMethodImports() as import>
import(${import})
</#list>