% Generated by maven-r-jsr223-plugin: do not edit by hand

\name{J${class.getName()}}

\alias{J${class.getName()}}

\title{${class.getValue("title")}}

\usage{\preformatted{
library(${model.getConfig().getPackageName()})
api <- J${class.getName()}$new();
}}

\description{
	${class.getDescription()!}
}

\details{
	${class.getDetails()!}
}

\examples{
<#list class.getMethods() as method>
## -----------------------------------
## Method `J${class.getName()}$${method.getName()}`
## -----------------------------------
	<#list method.getList("examples") as example>
  ${example}
	</#list>

</#list>
}

\keyword{java api}

\section{Methods}{
	\subsection{Public methods}{
		\itemize{
<#list class.getConstructorAndMethods() as method>
			\item \href{#method-${method.getName()}}{\code{J${class.getName()}$${method.getName()}(<#list method.getParameterNames() as paramName>${paramName}<#sep>, </#list>)}}
</#list>
			\item \code{J${class.getName()}$clone()}
			\item \code{J${class.getName()}$print()}
		}
	}

<#list class.getConstructorAndMethods() as method>
	\if{html}{\out{<hr>}}
	\if{html}{\out{<a id="method-${method.getName()}"></a>}}
	
	\subsection{Method \code{${method.getName()}()}}{
		${method.getDescription()}
	}

	\subsection{Usage}{
		\if{html}{\out{<div class="r">}}
		\preformatted{
  library(${model.getConfig().getPackageName()})
  api <- J${class.getName()}$new();
  api$${method.getName()}(<#list method.getParameterNames() as paramName>${paramName}<#sep>, </#list>)
		}
		\if{html}{\out{</div>}}
	}
	
	\subsection{Arguments}{
		\if{html}{\out{<div class="arguments">}}
		\describe{
			\itemize{
	<#list method.getParameterNames() as paramName>
				\item{${method.getParameterDescription(paramName)}}{ - (java expects a ${method.getParameterType(paramName)})}
	</#list>
			}
		}
		\if{html}{\out{</div>}}
	}

	\subsection{Returns}{
	<#if method.isFluent()>
		the J${class.getName()} itself
	<#else>
		${method.getReturnType()}: ${method.getValue("return")!}
	</#if>
	}

	\subsection{Examples}{
		\if{html}{\out{<div class="r example copy">}}
		\preformatted{
	<#list method.getList("examples") as example>
  ${example}
	</#list>
		}
		\if{html}{\out{</div>}}
	}
</#list>
}