% Generated by maven-r-jsr223-plugin: do not edit by hand
\name{java${class.getName()}}
\title{${class.getValue("title")}}
\usage{
	library(${class.getValue("packageName")})
	api <- java${class.getName()}();
}
\description{
${class.getValue("description")!}
}
\value{returns an S6 jsr223 groovy execution engine containing the instance of ${class.getName()} named x}
\keyword{java api}
