% Generated by maven-r-jsr223-plugin: do not edit by hand

\name{${class.getSimpleName()}}

\alias{${class.getSimpleName()}}

\title{${class.getTitle()}}

\usage{\preformatted{
library(${model.getConfig().getPackageName()})
J = JavaApi$new();
instance <- J$${class.getSimpleName()}$new(...);
}}

\description{
	${class.getDescription()!}
}

\details{
	${class.getDetails()!}
}

\examples{
<#list class.getMethods() as method>
## -----------------------------------
## Method `${class.getSimpleName()}$${method.getName()}`
## -----------------------------------
	<#list method.getAnnotationList("examples") as example>
  ${example}
	</#list>

</#list>
}

\keyword{java api}

\section{Methods}{
	\subsection{Constructors}{
		\itemize{
<#assign method=class.getConstructor()>
			\item \href{#method-${method.getName()}}{\code{J$${class.getSimpleName()}$${method.getName()}(${method.getParameterCsv()})}}
		}
	}
	\subsection{Static methods}{
		\itemize{
<#list class.getStaticMethods() as method>
			\item \href{#method-${method.getName()}}{\code{J$${class.getSimpleName()}$${method.getName()}(${method.getParameterCsv()})}}
</#list>
		}
	}
	\subsection{Instance methods}{
		\itemize{
<#list class.getInstanceMethods() as method>
			\item \href{#method-${method.getName()}}{\code{instance$${method.getName()}(${method.getParameterCsv()})}}
</#list>
			\item \code{instance$clone()}
			\item \code{instance$print()}
		}
	}

<#list class.getConstructorAndMethods() as method>
	\if{html}{\out{<hr>}}
	\if{html}{\out{<a id="method-${method.getName()}"></a>}}
	
	\subsection{Method \code{${method.getName()}()}}{
		${method.getDescription()}
	}

	\subsection{Usage}{
		\if{html}{\out{<div class="r">}}
		\preformatted{
	<#if method.isStatic()>
  library(${model.getConfig().getPackageName()})
  J <- JavaApi$new()
  J$${class.getSimpleName()}$${method.getName()}(${method.getParameterCsv()})
	<#else>
  library(${model.getConfig().getPackageName()})
  J <- JavaApi$new()
  instance <- J$${class.getSimpleName()}$new(...);
  instance$${method.getName()}(${method.getParameterCsv()})
  	</#if>
		}
		\if{html}{\out{</div>}}
	}
	
	\subsection{Arguments}{
		\if{html}{\out{<div class="arguments">}}
		\describe{
			\itemize{
	<#list method.getParameterNames() as paramName>
				\item{${method.getParameterDescription(paramName)}}{ - (java expects a ${method.getParameterType(paramName)})}
	</#list>
			}
		}
		\if{html}{\out{</div>}}
	}

	\subsection{Returns}{
	<#if method.isFactory()>
		R6 ${method.getReturnType().getSimpleName()} object: ${method.getAnnotationValue("return")!}
	<#else>
		${method.getReturnType()}: ${method.getAnnotationValue("return")!}
	</#if>
	}

	\subsection{Examples}{
		\if{html}{\out{<div class="r example copy">}}
		\preformatted{
	<#list method.getAnnotationList("examples") as example>
  ${example}
	</#list>
		}
		\if{html}{\out{</div>}}
	}
</#list>
}